apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: NodePort
  externalIPs:
        - 3.216.80.117
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
    nodePort: 30000
  selector:
    app: flink
    component: jobmanager
