---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: sparkWorkerApp
  minReadySeconds: 5

  template:
    metadata:
      labels:
        app: sparkWorkerApp
    spec:
      hostname: spark-worker-host  
      containers:
        - name: spark-worker
          image: 18.206.87.122:5000/spark:latest
          ports:
            - containerPort: 7078
            - containerPort: 7079
            - containerPort: 8081
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "1"
            - name: SPARK_HOME
              value: "/spark-3.2.0-bin-hadoop3.2"
          imagePullPolicy: Always 
          command: ["$(SPARK_HOME)/sbin/start-worker.sh"]
          args: ["spark://spark-master-service:7077", "--properties-file", "$(SPARK_HOME)/conf/spark-worker.conf"]
...
